var techId = document.getElementById('tech');
var tech = [
    'techcrunch.com',
    'TechCrunch',
    'thenextweb.com',
    'The Next Web',
    'wired.com',
    'Wired',
    'cnet.com',
    'c|net',
    'gizmag.com',
    'Gizmag',
    'engadget.com',
    'Engadget',
    'gizmodo.com',
    'Gizmodo',
    'theverge.com',
    'The Verge',
    'technorati.com',
    'Technorati',
    'techradar.com',
    'TechRadar',
    'techtimes.com',
    'Tech Times',
    'lifehacker.com',
    'Lifehacker',
    'lycos.com',
    'Lycos',
    'pcworld.com',
    'PCWorld',
    'pcmag.com',
    'PC Mag',
    'popsci.com',
    'Popsci',
    'tech2.com',
    'Tech2',
    'huffingtonpost.com/tech',
    'Huffpost Tech',
    'slashdot.org',
    'Slashdot',
    'softonic.com',
    'Softonic',
    'arstechnica.com',
    'Ars Technica',
    'polygon.com',
    'Polygon',
    'ubergizmo.com',
    'Ubergizmo',
    'slashgear.com',
    'SlashGear',
    'makeuseof.com',
    'Makeuseof',
    'techspot.com',
    'TechSpot',
    'digitaltrends.com',
    'Digital Trends',
    'venturebeat.com',
    'VentureBeat',
    'betanews.com',
    'BetaNews',
    'techshout.com',
    'TechShout',
    'cpanel.net',
    'cPanel',
    'techlicious.com',
    'Techlicious',
    'ampproject.org',
    'AMP',
    'idigitaltimes.com',
    'iDigitalTimes',
    'lifehack.org',
    'LifeHack',
    'readwrite.com',
    'Readwrite',
    'atari.com',
    'Atari',
    'pctechmag.com',
    'PC Tech Mag',
    'f6s.com',
    'F6s',
    'kongregate.com',
    'Kongregate',
    'addictinggames.com',
    'Addicting Games',
    'bgr.com',
    'BGR',
    'unity3d.com',
    'Unity',
    'spectrum.ieee.org',
    'IEEE',
    'dev.to',
    'Dev',
    '9to5mac.com',
    '9to5Mac',
    'gigaom.com',
    'Gigaom',
    'techmeme.com',
    'TechMeme',
    'infoworld.com',
    'InfoWorld',
    'cio.com',
    'CIO',
    'geek.com',
    'Geek',
    'socialmediatoday.com',
    'SocialMediaToday',
    'ign.com',
    'IGN',
    'intel.com',
    'Intel',
    'cisco.com',
    'Cisco',
    'thisiscolossal.com',
    'Colossal',
    'producthunt.com',
    'Product Hunt',
    'techdirt.com',
    'Techdirt.',
    'cmo.com',
    'CMO',
    'appleinsider.com',
    'AppleInsider',
    'www.mattcutts.com/blog',
    'Matt Cutts',
    'wolframalpha.com',
    'WolframAlpha',
    'builtwith.com',
    'BuiltWith',
    'mit.edu',
    'MIT',
    'programmableweb.com/apis/directory',
    'API',
    'recode.com',
    'Re/code',
    'c9.io',
    'Cloud9',
    'googleblog.blogspot.com',
    'GoogleBlog',
    'visualcapitalist.com',
    'Capitalist',
    'devpost.com',
    'Devpost',
    'thedailywtf.com',
    'Daily WTF',
    'macrumors.com',
    'MacRumors',
    'droid-life.com',
    'Droid Life',
    'eurogamer.net',
    'Eurogamer',
    'techtarget.com',
    'TechTarget',
    'techrepublic.com',
    'TechRepublic',
    'vectr.com/new',
    'Vectr',
    'discordapp.com',
    'Discord',
    'www.cs.oberlin.edu/~kuperman/help/vim/',
    'Vim'
];
for (var i = 0; i < tech.length; i = i + 2) {
    techId.innerHTML +=
        '<a target="_blank" href="https://' +
        tech[i] +
        '">' +
        tech[i + 1] +
        '</a> &sdot; ';
}

var usefulId = document.getElementById('useful');
var useful = [
    'https://ask.com',
    'Ask',
    'https://answers.com',
    'Answers',
    'https://maps.google.com',
    'Google Maps',
    'https://dummies.com',
    'Dummies',
    'https://10minutemail.com',
    '10 Minute Mail',
    'https://thesaurus.com',
    'Thesaurus',
    'https://uber.com',
    'Uber',
    'https://howstuffworks.com',
    'HowStuffWorks',
    'https://wikihow.com',
    'WikiHow',
    'https://ehow.com',
    'eHow',
    'https://translate.google.pl',
    'Translate',
    'https://trustedreviews.com',
    'TrustedReviews',
    'https://investopedia.com',
    'Investopedia',
    'https://openstreetmap.org',
    'OpenStreetMap',
    'https://mapquest.com',
    'MapQuest',
    'https://citysearch.com',
    'Citysearch',
    'https://www.wunderground.com',
    'WU',
    'https://weather.com',
    'Weather',
    'https://any.do',
    'AnyDo',
    'https://tvguide.com',
    'TV Guide',
    'https://xe.com',
    'XE',
    'https://tripadvisor.com',
    'TripAdvisor',
    'https://healthline.com',
    'Healthline',
    'https://medicare.gov',
    'Medicare',
    'https://calm.com',
    'Calm',
    'https://allrecipes.com',
    'Allrecipes',
    'https://allmenus.com',
    'Allmenus',
    'https://menuism.com',
    'Menuism',
    'https://fitbit.com',
    'Fitbit',
    'https://endomondo.com',
    'Endomondo',
    'https://newser.com',
    'Newser',
    'https://wordreference.com',
    'WordReference',
    'https://knowyourmeme.com',
    'Know Your Meme',
    'https://aw-snap.info',
    'Aw Snap',
    'https://getpocket.com',
    'Pocket',
    'https://state.gov',
    'State',
    'http://www.livescore.com',
    'LiveScore',
    'https://airbnb.com',
    'Airbnb',
    'https://couchsurfing.com',
    'CouchSurfing',
    'https://earthables.com',
    'Earthables',
    'https://timeanddate.com',
    'Timeanddate',
    'https://urbandictionary.com/define.php?term=Fulck',
    'UrbanDictionary',
    'https://picmonkey.com',
    'PicMonkey',
    'https://dictation.io',
    'Dictation',
    'https://charge.com',
    'Charge',
    'https://gutenberg.org',
    'Gutenberg',
    'https://drugs.com',
    'Drugs',
    'https://flightradar24.com',
    'Flightradar24',
    'https://britannica.com',
    'Britannica',
    'https://twentytwowords.com',
    '22 Words',
    'https://rome2rio.com',
    'Rome2rio',
    'https://keen.com',
    'Keen',
    'https://dev.w3.org/html5/html-author/charref',
    'Entities',
    'http://googlefeud.com',
    'Feud',
    'https://logomakr.com',
    'LogoMakr',
    'https://squarespace.com',
    'Squarespace',
    'https://hipmunk.com',
    'Hipmunk',
    'http://vidmax.com',
    'Vidmax',
    'http://mapcrunch.com',
    'MapCrunch',
    'https://rapportive.com',
    'Rapportive',
    'https://crooksandliars.com',
    'Crooks&Liars',
    'http://sentence.yourdictionary.com',
    'Sentence',
    'https://smartlook.com',
    'Smartlook',
    'https://positivityblog.com',
    'Positivity',
    'http://usdebtclock.org',
    'Debt Clock',
    'http://good-tutorials.com',
    'Tutorials',
    'https://cia.gov/library/publications/the-world-factbook',
    'CIA Factbook',
    'https://proxysite.com',
    'ProxySite',
    'https://www.coindesk.com/price',
    'Bitcoin Price',
    'http://jspaint.ml',
    'Paint',
    'https://havocscope.com/black-market-prices/marijuana-prices',
    'Marijuana Price',
    'http://buymarijuanaonlinenow.com',
    'Buy Weed',
    'http://lightning.network',
    'Lightning Network',
    'https://asana.com',
    'Asana',
    'https://trello.com',
    'Trello',
    'https://slack.com',
    'Slack',
    'https://kialo.com',
    'Kialo',
    'http://www.gematrinator.com/calculator/index.php',
    'Gematrinator'
];
for (var i = 0; i < useful.length; i = i + 2) {
    usefulId.innerHTML +=
        '<a target="_blank" href="' +
        useful[i] +
        '">' +
        useful[i + 1] +
        '</a> &sdot; ';
}

var trendsId = document.getElementById('trends');
var trends = [
    'ted.com',
    'Ted',
    'salon.com',
    'Salon',
    'thrillist.com',
    'Thrillist',
    'businessinsider.com',
    'Business Insider',
    'thoughtcatalog.com',
    'Catalog',
    'spectator.co.uk',
    'Spectator',
    'inc.com',
    'Inc',
    'ranker.com',
    'Ranker',
    'likes.com',
    'Likes',
    'toptenz.net',
    'Toptenz',
    'guff.com',
    'Guff',
    'goodreads.com',
    'Goodreads',
    'refinery29.com',
    'Refinery29',
    'thetoptens.com',
    'Top 10',
    'memes.com',
    'Memes',
    'begrizly.com',
    'Grizly',
    'rare.us',
    'Rare',
    'ozy.com',
    'Ozy',
    'liveleak.com',
    'LiveLeak',
    'theonion.com',
    'The Onion',
    'pogo.com',
    'Pogo',
    'awwwards.com',
    'Awwwards',
    'line25.com',
    'Line25',
    'justcreative.com',
    'JustCreative',
    'minimums.com',
    'Minimums',
    'mentalfloss.com',
    'Mental Floss',
    'thinkprogress.org',
    'Think Progress',
    'heavy.com',
    'Heavy',
    'americanthinker.com',
    'Thinker',
    'illusion.scene360.com',
    'Illusion',
    'trendland.com',
    'Trendland',
    'chic.com',
    'Chic',
    'cowbird.com',
    'Cowbird',
    'digitalcollections.nypl.org',
    'NYPL',
    'nationalgallery.org.uk',
    'National Gallery',
    'christies.com',
    'Christie’s',
    'roundpeg.biz',
    'Roundpeg',
    'okfn.org',
    'OKFN',
    'likecool.com',
    'LikeCool',
    'creativemarket.com',
    'Creative',
    'sothebys.com',
    'Sotheby’s',
    'artsy.net',
    'Artsy',
    'nextag.com',
    'NexTag',
    'fromupnorth.com',
    'From up North',
    'nature.com',
    'Nature',
    'zero-magazine.co.uk',
    'Zero',
    'jezebel.com',
    'Jezebel',
    'fashionista.com',
    'Fashionista',
    'codepen.io',
    'CodePen',
    'google.com/maps/streetview/#art-project',
    'Art Project',
    'boingboing.net',
    'BoingBoing',
    'complex.com',
    'Complex',
    'models.com',
    'Models',
    'fusion.net',
    'Fusion',
    'academia.edu',
    'Academia',
    'project-syndicate.org',
    'Syndicate',
    'ethereum.org',
    'Ethereum',
    'evolutionofweb.appspot.com',
    'Evolution',
    '1000.chromeexperiments.com',
    '1000',
    'therichest.com',
    'TheRichest',
    'hotair.com',
    'HotAir',
    'consumerist.com',
    'Consumerist',
    'zerohedge.com',
    'Zero Hedge',
    'freedomhouse.org',
    'Freedom House',
    'esquire.com',
    'Esquire',
    'sciencedirect.com',
    'ScienceDirect',
    'mediaite.com',
    'Mediaite',
    'openculture.com',
    'Open Culture',
    'debate.org',
    'Debate',
    'grist.org',
    'Grist',
    'mic.com',
    'Mic',
    'ello.co',
    'Ello',
    'providr.com',
    'Providr',
    'uxpin.com',
    'UXPin',
    'evernote.com',
    'Evernote',
    'inbound.org',
    'Inbound',
    'theoutline.com',
    'The Outline',
    'adage.com',
    'Ad Age',
    'fact-checkers.org',
    'Fact-Checkers',
    'cambridgeanalytica.org',
    'Cambridge Analytica'
];
for (var i = 0; i < trends.length; i = i + 2) {
    trendsId.innerHTML +=
        '<a target="_blank" href="https://' +
        trends[i] +
        '">' +
        trends[i + 1] +
        '</a> &sdot; ';
}

var funnyId = document.getElementById('funny');
var funny = [
    '9gag.com',
    '9gag',
    'funnyordie.com',
    'Funny Or Die',
    'collegehumor.com',
    'CollegeHumor',
    'break.com',
    'Break',
    'dailyhaha.com',
    'Dailyhaha',
    'giphy.com',
    'Giphy',
    'gfycat.com',
    'Gfycat',
    'pranksters.com',
    'Pranksters',
    'theoatmeal.com',
    'The Oatmeal',
    'awkwardfamilyphotos.com',
    'Awkward Family Photos',
    'jokes4us.com',
    'Jokes4us',
    'laughfactory.com/jokes',
    'Laugh Factory',
    'cracked.com',
    'Cracked',
    'xkcd.com',
    'XKCD',
    'funnywebsite.com',
    'FunnyWebsite',
    'bored.com',
    'Bored',
    'cheezburger.com',
    'Cheezburger',
    'funnyjunk.com',
    'FunnyJunk',
    'smosh.com',
    'Smosh',
    'kickvick.com',
    'KickVick',
    'ebaumsworld.com',
    'eBaum’s World',
    'short-funny.com',
    'Short-Funny',
    'gocomics.com',
    'GoComics',
    'ferryhalim.com/orisinal/',
    'Orisinal',
    'kickasshumor.com',
    'Kickass Humor',
    'jokes.cc.com',
    'Jokes',
    'uncyclopedia.co',
    'Uncyclopedia',
    'textastrophe.com',
    'Textastrophe',
    'metacafe.com',
    'Metacafe',
    'mugshots.com',
    'Mugshots',
    'engrish.com',
    'Engrish',
    'epicfail.com',
    'EpicFail',
    'neatorama.com',
    'Neatorama',
    'laughingsquid.com',
    'Laughing Squid',
    'boredpanda.com',
    'Bored Panda',
    'eatliver.com',
    'EatLiver',
    'quickmeme.com',
    'Quickmeme',
    'uberhumor.com',
    'Uber Humor',
    'hooplaha.com',
    'HooplaHa',
    'peopleofwalmart.com',
    'People of Walmart',
    'stupidvideos.com',
    'StupidVideos',
    'mandatory.com',
    'Mandatory',
    'thedailyfever.com',
    'TDF',
    'www.picturesofwalls.com',
    'Pictures of Walls',
    'dilbert.com',
    'Dilbert',
    'funpalaces.co.uk',
    'Fun Palaces',
    'boringz.com',
    'Boringz',
    'me.me',
    'Me.me'
];
for (var i = 0; i < funny.length; i = i + 2) {
    funnyId.innerHTML +=
        '<a target="_blank" href="https://' +
        funny[i] +
        '">' +
        funny[i + 1] +
        '</a> &sdot; ';
}

var weirdId = document.getElementById('weird');
var weird = [
    'https://4chan.org',
    '4chan',
    'https://imgur.com',
    'Imgur',
    'https://nerdist.com',
    'Nerdist',
    'http://www.theuselessweb.com',
    'The Useless Web',
    'https://pointless.com',
    'Pointless',
    'http://www.fallingfalling.com',
    'Falling',
    'https://procatinator.com',
    'Procatinator',
    'https://rainymood.com',
    'Rainy Mood',
    'http://baconsizzling.com',
    'Bacon Sizzling',
    'https://theinternetfireplace.com',
    'Fireplace',
    'http://www.farfotsel.com',
    'Farfotsel',
    'http://www.staggeringbeauty.com',
    'Staggering Beauty',
    'http://sanger.dk',
    'Sanger',
    'https://corgiorgy.com',
    'Corgiorgy',
    'http://intotime.com',
    'Intotime',
    'http://partridgegetslucky.com',
    'Partridge',
    'https://omfgdogs.com',
    'Omfgdogs',
    'http://heeeeeeeey.com',
    'Hey',
    'http://hooooooooo.com',
    'Ho',
    'http://make-everything-ok.com',
    'Make OK',
    'https://zoomquilt.org',
    'Zoomquilt',
    'http://codeofrob.com',
    'CodeOfRob',
    'https://lingscars.com',
    'LingsCars',
    'http://feedthehead.net',
    'Feed the Head',
    'https://www.barcinski-jeanjean.com/entries/line3d',
    'Line',
    'http://trionfi.com',
    'Trionfi',
    'http://anomalies-unlimited.com',
    'Anomailes',
    'http://www.ocearch.org/#SharkTracker',
    'SharkTracker',
    'https://waitbutwhy.com',
    'WaitButWhy',
    'http://anasomnia.com',
    'AnaSomnia',
    'https://erowid.org',
    'Erowid',
    'http://giantbatfarts.com',
    'Bats',
    'http://973-eht-namuh-973.com',
    '973-eht-namuh',
    'https://stupid.com',
    'Stupid',
    'http://pointerpointer.com',
    'Pointer',
    'https://tfes.org',
    'Flat Earth',
    'http://thisman.org',
    'This Man',
    'https://theendofreason.com',
    'End of Reason',
    'https://rock-paper-scissors-game.com',
    'RPS',
    'http://z0r.de',
    'Z0r',
    'http://universe-people.com',
    'Universe People',
    'https://mynoise.net/NoiseMachines/greyNoiseGenerator.php',
    'Grey Noise',
    'http://wwwwwwwww.jodi.org',
    'Jodi',
    'http://locklip.com',
    'Locklip',
    'http://exitmundi.nl',
    'ExitMundi',
    'https://fractalfantasy.net',
    'Fractal Fantasy',
    'http://pixyland.org/peterpan',
    'Peter Pan',
    'http://thefacesoffacebook.com/',
    'Faces of Facebook',
    'https://html5zombo.com',
    'Zombo',
    'http://www.windows93.net/',
    'Win93',
    'http://www.crazyshit.com',
    'Crazy Shit',
    'http://amishrakefight.org/gfy',
    'GFY',
    'https://hmpg.net',
    'The End of Internet'
];
for (var i = 0; i < weird.length; i = i + 2) {
    weirdId.innerHTML +=
        '<a target="_blank" href="' +
        weird[i] +
        '">' +
        weird[i + 1] +
        '</a> &sdot; ';
}

var adultId = document.getElementById('adult');
var adult = [
    'xvideos.com',
    'Xvideos',
    'pornhub.com',
    'Pornhub',
    'redtube.com',
    'Redtube',
    'xhamster.com',
    'xHamster',
    'xnxx.com',
    'Xnxx',
    'youporn.com',
    'YouPorn',
    'livejasmin.com',
    'LiveJasmin',
    'adultfriendfinder.com',
    'AFF',
    'cam4.com',
    'Cam4',
    'xbabe.com',
    'XBabe',
    'nudevista.com',
    'Nudevista',
    'flirt4free.com',
    'Flirt4free',
    'bongacams.com',
    'BongaCams',
    'txxx.com',
    'Txxx',
    'g.e-hentai.org',
    'Hentai',
    'hclips.com',
    'Hclips',
    'chaturbate.com',
    'Chaturbate',
    'rk.com',
    'RealityKings',
    'upornia.com',
    'Upornia',
    'tube8.com',
    'Tube8',
    'porn.com',
    'Porn',
    '4tube.com',
    '4tube',
    'myex.com',
    'MyEx',
    'hotmilfclips.com',
    'Hot Milf',
    'bangbrosnetwork.com',
    'BangBros',
    'pornfun.com',
    'PornFun',
    'pornhub.com',
    'PornHub',
    'blacked.com',
    'Blacked',
    'adam4adam.com',
    'Adam',
    'gif-porn.com',
    'Gif-Porn',
    'zoig.com',
    'Zoig',
    'my18tube.com',
    'My18Tube',
    'xxxbunker.com',
    'Bunker',
    'mofosex.com',
    'Mofo',
    'tnaflix.com',
    "T'nA",
    'spankbang.com',
    'SpankBang',
    'wetplace.com',
    'WetPlace',
    'fux.com',
    'Fux',
    'slutload.com',
    'SlutLoad',
    'orgasm.com',
    'Orgasm',
    'beeg.com',
    'Beeg',
    'x-art.com',
    'X-art',
    'sexu.com',
    'Sexu',
    'youjizz.com',
    'YouJizz',
    'fapdu.com',
    'Fapdu',
    'h2porn.com',
    'H2',
    'iwank.tv',
    'iWank',
    'updatetube.com',
    'UpdateTube',
    'vintagevideos.xxx',
    'Vintage',
    'bigtits.com',
    'BigTits',
    'virtualporn360.com',
    'VR Porn',
    'nuvid.com',
    'Nuvid',
    'pornotube.com',
    'PornoTube',
    'brazzers.com',
    'Brazzers',
    'eroprofile.com',
    'EroProfile',
    'long.xxx',
    'Long',
    'drtuber.com',
    'Dr Tuber',
    'efukt.com',
    'Efukt',
    'czechfantasy.com',
    'Czech Fantasy',
    'pornerbros.com',
    'PornerBros',
    'fakeporn.tv',
    'Fake Porn',
    'shecams.com',
    'SheCams',
    'manyvids.com',
    'Many Vids',
    'bffs.com',
    'Bffs',
    'shameless.com',
    'Shameless',
    'vitalyuncensored.com',
    'Vitaly Uncensored'
];
for (var i = 0; i < adult.length; i = i + 2) {
    adultId.innerHTML +=
        '<a target="_blank" href="https://' +
        adult[i] +
        '">' +
        adult[i + 1] +
        '</a> &sdot; ';
}

function adultSites() {
    document.querySelector('.line').style.display =
        document.querySelector('.line').style.display == 'none'
            ? 'block'
            : 'none';

    document.querySelector('.is18').borderColor =
        document.querySelector('.line').style.display !== 'block'
            ? 'rgba(255, 0, 0, .8)'
            : 'rgba(0, 0, 0, .4)';

    var forAdults = document.querySelectorAll('.adult');
    for (var i = 0; i < forAdults.length; i++) {
        forAdults[i].classList.toggle('hide');
    }
}

var elem2 = document.getElementById('top2');
data2 = [];

for (var i in data2) {
    elem2.innerHTML += `<a target="_blank" href="https://${data2[i][0]}" >
        <img src=${data2[i][1]} title="Go to <span>#${parseInt(i) +
        234}</span><p><img src=${data2[i][1]}><p>${
        data2[i][0]
        }" alt="fulck" onerror="replaceImg(this)" />
    </a>`;
}

tippy('img', {
    delay: 100,
    arrow: true,
    size: 'large',
    duration: 500,
    animation: 'shift-away',
    placement: 'right',
    theme: 'fulck'
});

let moon = document.querySelector('#mode').innerHTML;
let logo = document.querySelector('.logo').style.backgroundImage;

document.querySelector('#mode').addEventListener('click', function () {
    this.innerHTML = this.innerHTML == moon ? '&#9788;' : moon;
    document.querySelector('.logo').style.backgroundImage =
        document.querySelector('.logo').style.backgroundImage == logo
            ? 'url("logo-white.svg")'
            : logo;

    document.querySelector('body').classList.toggle('night');
    document.querySelector('.lista').classList.toggle('night');
    document.querySelectorAll('.lista img').forEach(el => {
        //el.classList.toggle('night-border');
        //el.style.height = '1em';
    });
});

document.querySelector('#abc').addEventListener('click', function () {
    data.sort((a, b) => a[0].localeCompare(b[0]));

    elem.innerHTML = '';
    for (var i in data) {
        elem.innerHTML += `<a class="${data[i][3] == 'adult' &&
            'adult hide'}" target="_blank" href="https://${data[i][0]}" >
        <img src=${data[i][1]} alt="fulck" onerror="replaceImg(this)" />
    </a>`;
    }
});
