var newsId = document.getElementById('news');
var news = ['cnn.com', 'CNN', 'bbc.co.uk', 'BBC', 'foxnews.com', 'Fox News', 'abcnews.go.com', 'ABC News', 'cnbc.com', 'CNBC', 'reuters.com', 'Reuters', 'news.sky.com', 'Sky News', 'cbsnews.com', 'CBS News', 'news.yahoo.com', 'Yahoo News', 'nytimes.com', 'New York Times', 'huffingtonpost.com', 'Huffington Post', 'washingtonpost.com', 'Washington Post', 'usnews.com', 'US News', 'usatoday.com', 'USA Today', 'bloomberg.com', 'Bloomberg', 'forbes.com', 'Forbes', 'ft.com', 'Financial Times', 'time.com', 'Time', 'wsj.com', 'Wall Street Journal', 'nypost.com', 'New York Post', 'politico.com', 'Politico', 'newsweek.com', 'Newsweek', 'usmagazine.com', 'US Weekly', 'dailymail.co.uk', 'Daily Mail', 'independent.co.uk', 'The Independent', 'economist.com', 'Economist', 'mirror.co.uk', 'Mirror', 'newyorker.com', 'New Yorker', 'telegraph.co.uk', 'The Telegraph', 'theguardian.com', 'The Guardian', 'c-span.org', 'C-Span', 'chicagotribune.com', 'Chicago Tribune', 'latimes.com', 'LA Times', 'nydailynews.com', 'NY Daily News', 'townhall.com', 'Townhall', 'patch.com', 'Patch', 'observer.com', 'Observer', 'examiner.com', 'Examiner', 'newsvine.com', 'Newsvine', 'npr.org', 'NPR', 'attn.com', 'attn:', 'wn.com', 'WN', 'cox.net', 'Cox', 'euronews.com', 'Euronews', 'News.com.au', 'News AU', 'adweek.com', 'Adweek', 'theatlantic.com', 'Atlantic', 'sfgate.com', 'SFGate', 'vox.com', 'Vox', 'thehill.com', 'The Hill', 'qz.com', 'Qz', 'fortune.com', 'Fortune', 'rawstory.com', 'RawStory', 'cbc.ca/news', 'CBC News', 'aljazeera.com', 'Al Jazeera', 'jpost.com', 'JPost', 'dw.com', 'DW', 'en.wikinews.org', 'Wikinews', 'globalnews.ca', 'Global News', 'nationalpost.com', 'National Post', 'indiatimes.com', 'IndiaTimes', 'thehindu.com', 'The Hindu', 'spiegel.de', 'Der Spiegel', 'rt.com', 'RT News', 'tass.ru', 'Tass', 'livemint.com', 'Livemint', 'thestar.com', 'The Star', 'ibtimes.com', 'IB Times', 'newsmax.com', 'Newsmax', 'web.de', 'Web.de', 'bild.de', 'Bild', 'onet.pl', 'Onet', 'seznam.cz', 'Seznam', 'elpais.com', 'El Pais', 'france24.com', 'France24', 'money.cnn.com', 'Money', 'standard.co.uk', 'Standard', 'theglobeandmail.com', 'Globe & Mail', 'foxbusiness.com', 'Fox Business', 'breakingnews.com', 'Breaking News', 'suntimes.com', 'Sun Times', 'upi.com', 'UPI', 'theweek.com', 'The Week', 'consortiumnews.com', 'Consortium News', 'corbettreport.com', 'Corbett Report', 'newsbud.com', 'Newsbud', 'theantimedia.org', 'AntiMedia', 'breitbart.com', 'Breitbart'];
for (var i = 0; i < news.length; i = i + 2) {
    newsId.innerHTML += '<a target="_blank" href="https://' + news[i] + '">' + news[i + 1] + '</a> &sdot; ';
}

var shoppingId = document.getElementById('shopping');
var shopping = ['amazon.com/gp/goldbox', 'Amazon', 'aliexpress.com', 'AliExpress', 'alibaba.com', 'Alibaba', 'walmart.com', 'Walmart', 'ebay.com', 'eBay', 'bestbuy.com', 'Best Buy', 'snapdeal.com', 'Snapdeal', 'shopify.com', 'Shopify', 'target.com', 'Target', 'etsy.com', 'Etsy', 'ikea.com', 'Ikea', 'overstock.com', 'Overstock', 'costco.com', 'Costco', 'macys.com', 'Macy\'s', 'sears.com', 'Sears', 'kohls.com', 'Kohl’s', 'newegg.com', 'Newegg', 'jcpenney.com', 'JCPenney', 'jabong.com', 'Jabong', 'flipcart.com', 'FlipCart', 'toysrus.com', 'Toys’R’Us', 'slickdeals.net', 'Slickdeals', 'shop.com', 'Shop', 'buy.com', 'Buy', 'zillow.com', 'Zillow', 'barnesandnoble.com', 'Barnes & Noble', 'homedepot.com', 'Home Depot', 'indulged.com', 'Indulged', 'livingsocial.com', 'LivingSocial', 'groupon.com', 'Groupon', 'buycostumes.com', 'Costumes', 'forever21.com', 'Forever 21', 'moddeals.com', 'Moddeals', 'thisnext.com', 'ThisNext', 'zazzle.com', 'Zazzle', 'asda.com', 'Asda', 'rue21.com', 'Rue 21', 'debshops.com', 'Deb', 'zappos.com', 'Zappos', 'okthestore.com', 'OK', 'nordstrom.com', 'Nordstrom', 'dx.com', 'DealExtreme', 'asos.com', 'ASOS', 'staples.com', 'Staples', 'fab.com', 'Fab', 'argos.co.uk', 'Argos', 'kmart.com', 'Kmart', 'tesco.com', 'Tesco', 'mango.com', 'Mango', 'marksandspencer.com', 'M&S', 'beauty.com ', 'Beauty', 'net-a-porter.com', 'Net-a-porter', 'hsn.com', 'HSN', 'wards.com', 'Wards', 'fanatics.com', 'Fanatics', 'wayfair.com', 'Wayfair', '6pm.com', '6pm', 'Yoox.com', 'Yoox', 'bloomingdales.com', 'Bloomingdale’s', 'shopbop.com', 'Shopbop', 'sephora.com', 'Sephora', 'gap.com', 'Gap', 'iherb.com', 'iHerb', 'victoriassecret.com', 'Victoria’s Secret', 'jcrew.com', 'J.Crew', 'ralphlauren.com', 'Ralph Lauren', 'qvc.com', 'QVC', 'dsw.com', 'DSW', 'rosegal.com', 'Rosegal', 'gifts.com', 'Gifts', 'shop.lego.com', 'Lego', 'keds.com', 'Keds', 'nike.com', 'Nike', 'adidas.com', 'Adidas', 'ae.com', 'AE', 'calvinklein.com', 'CK', 'hm.com', 'H&M', 'reebok.com', 'Reebok', 'samsung.com', 'Samsung', 'store.hp.com', 'HP', 'dell.com', 'Dell', 'canon.com', 'Canon', 'sony.com', 'Sony', 'nikon.com', 'Nikon', 'rokit.co.uk', 'Rokit', 'topshop.com', 'Topshop', 'luxurybazaar.com', 'Luxury Bazaar', 'stylebob.com', 'StyleBob', 'pixiemarket.com', 'Pixie', 'vans.com', 'Vans', 'avenue32.com', 'Avenue 32', 'keep.com', 'Keep', 'pendleton-usa.com', 'Pendleton', 'oaknyc.com', 'Oak', 'wish.com', 'Wish', 'starter.com', 'Starter', 'oki-ni.com', 'Oki', 'store.americanapparel.net', 'American Apparel', 'themountain.com', 'The Mountain', 'arrohome.com', 'Arro', 'gopro.com', 'GoPro', 'tommy.com', 'Tommy', 'mignon-shop.com', 'Mignon', 'baublebar.com', 'Bablebar', 'vestiairecollective.com', 'Vestiaire', 'gilt.com', 'Gilt', 'trulia.com', 'Trulia', 'realtor.com', 'Realtor'];
for (var i = 0; i < shopping.length; i = i + 2) {
    shoppingId.innerHTML += '<a target="_blank" href="https://' + shopping[i] + '">' + shopping[i + 1] + '</a> &sdot; ';
}

var entertainmentId = document.getElementById('entertainment');
var entertainment = ['netflix.com', 'Netflix', 'imdb.com', 'IMDb', 'diply.com', 'Diply', 'espn.go.com', 'ESPN', 'eonline.com', 'E!', 'variety.com', 'Variety', 'vice.com', 'Vice', 'cosmopolitan.com', 'Cosmopolitan', 'playboy.com', 'Playboy', 'mtv.com', 'MTV', 'rollingstone.com', 'Rolling Stone', 'tmz.com', 'TMZ', 'veoh.com', 'Veoh', 'theladbible.com', 'LAD', 'hulu.com', 'Hulu', 'slate.com', 'Slate', 'topix.com', 'Topix', 'babble.com', 'Babble', 'timeout.com', 'Time Out', 'brainfall.com', 'Brainfall', 'lasvegas.com/shows-and-events/', 'Vegas', 'vogue.com', 'Vogue', 'bravotv.com', 'Bravo', 'tv.com', 'TV', 'thescene.com', 'The Scene', 'crackle.com', 'Crackle', 'rottentomatoes.com', 'Rotten Tomatoes', 'fandango.com', 'Fandango', 'yourdailydish.com', 'Your Daily Dish', 'nba.com', 'NBA', 'nfl.com', 'NFL', '247sports.com', '247Sports', 'goal.com', 'Goal', 'perezhilton.com', 'Perez Hilton', 'hollywood.com', 'Hollywood', 'vh1.com', 'VH1', 'hollywoodlife.com', 'Hollywood Life', 'avclub.com', 'AVClub', 'scifi.com', 'SciFi', 'findyourwaytooz.com', 'Oz', 'reel.com', 'Reel', 'zap2it.com', 'Zap2It', 'spin.com', 'Spin', 'billboard.com', 'Billboard', 'devour.com', 'Devour', 'popbitch.com', 'Popbitch', 'nme.com/news', 'NME', 'aardman.com', 'Aardman', 'deadline.com', 'Deadline', 'gawker.com', 'Gawker', 'ew.com', 'EW', 'thedailybeast.com', 'Daily Beast', 'damn.com', 'Damn!', 'pastemagazine.com', 'Paste', 'metro.co.uk', 'Metro', 'digitalspy.com', 'DigitalSpy', 'ok.co.uk', 'OK!', 'maxim.com', 'Maxim', 'empireonline.com', 'Empire', 'gq.com', 'GQ', 'instyle.com', 'InStyle', 'flare.com', 'Flare', 'fashionmagazine.com', 'Fashion', 'elle.com', 'Elle', 'redbook.com', 'Redbook', 'more.com', 'More', 'hellomagazine.com', 'Hello!', 'askmen.com', 'AskMen', 'thesun.co.uk', 'The Sun', 'page3.com', 'Page3', 'alternet.org', 'Alternet', 'infowars.com', 'InfoWars', 'tcm.com', 'TCM', 'justjared.com', 'Just Jared', 'disney', 'Disney', 'newsday.com', 'Newsday', 'bossip.com', 'Bossip', 'sheknows.com', 'Sheknows', 'masala.com', 'Masala', 'aramajapan.com', 'Arama', 'ancientx.com', 'AncientX', 'wetpaint.com', 'Webpaint', 'starwars.com', 'StarWars', 'deadspin.com', 'Deadspin', 'aceshowbiz.com', 'AceShowbiz', 'retronaut.com', 'Retronaut', 'vocativ.com', 'Vocativ', 'popsugar.com', 'Popsugar', 'zootoday.com', 'ZOO', 'zimbio.com', 'Zimbio', 'heatworld.com', 'Heat', 'thechive.com', 'theCHIVE', 'wonderwall.com', 'Wonderwall', 'wwe.com', 'WWE', 'radaronline.com', 'Radar', 'people.com', 'People', 'si.com', 'Sports Illustrated', 'kideos.com', 'Kideos', 'racked.com', 'Racked', 'sacred-texts.com', 'Sacred Text', 'kiwibox.com', 'Kiwibox', 'the-dots.com', 'The-Dots', 'solipsism.online', 'Solipsism', 'deezer.com', 'Deezer', 'celebritynetworth.com', 'Celebrity Net Worth', 'geoguessr.com', 'Geo Guessr'];
for (var i = 0; i < entertainment.length; i = i + 2) {
    entertainmentId.innerHTML += '<a target="_blank" href="https://' + entertainment[i] + '">' + entertainment[i + 1] + '</a> &sdot; ';
}
